/home/ubuntu/anaconda3/envs/bigdata2/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
